fruits = []
fruits.append('apple')
fruits.append('banana')
fruits.append('apple')
fruits.append('banana')
fruits.append('apple')
fruits.append('banana')
fruits.append('apple')
fruits.append('banana')
print(fruits)